<a href="https://colab.research.google.com/github/nobottle/codingtest-review/blob/main/03_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EB%8B%A4%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4%EC%9D%98_%EA%B3%84%EC%82%B0~3%EC%B8%B5%EC%8B%A0%EA%B2%BD%EB%A7%9D%EA%B5%AC%ED%98%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**다차원 배열***

In [13]:
import numpy as np
A=np.array([1,2,3,4])
print(A)

print(np.ndim(A)) #배열의 차원 수

print(A.shape)

print(A.shape[0])


[1 2 3 4]
1
(4,)
4


In [14]:
B=np.array([[1,2],[3,4],[5,6]])
print(B)

print(np.ndim(B))

print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [15]:
#행렬의 곱셈
A=np.array([[1,2],[3,4]])
print(A.shape)

B=np.array([[5,6],[7,8]])

print(B.shape)

print(np.dot(A,B)) #두 행렬의 곱 1차원이면 백터를,2차원이면 행렬 곱을 계산한다

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


In [16]:
A=np.array([[1,2,3],[4,5,6]])

print(A.shape)

B=np.array([[1,2],[3,4],[5,6]])

print(B.shape)

print(np.dot(A,B))

#곱은 첫번째 행렬 열수와 2번째 행렬 행의 원소 수가 같아야 한다!

(2, 3)
(3, 2)
[[22 28]
 [49 64]]


행렬
A(3,2)
B(2,4)
A*B=C(3,4)
계산 결과인 C의 형상은 A의 행수와 B의 열수로 된다!!


A(3,2).  B(2) 일 경우 A의 뒤쪽과 B가 일치해야한다


In [17]:
A=np.array([[1,2],[3,4],[5,6]])
print(A.shape)

B=np.array([7,8])
print(B.shape)

print(np.dot(A,B))

(3, 2)
(2,)
[23 53 83]


In [18]:
#신경망에서의 행렬 곱 1차원과 2차원배열의 경우 1차원을 앞에서 곱하면 2차원 행이랑 개수가 일치해야하고 뒤애서 곱하면 열에서 개수가 일치해야한다

'''
x w y 
(p.82참조)
'''
X=np.array([1,2])
print(X.shape)

W=np.array([[1,3,5],[2,4,6]])
print(W)

print(W.shape)

Y=np.dot(X,W)
print(Y)



(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)
[ 5 11 17]


3층 신경망 구현하기

x2>>>>>a1으로 뉴런이 향할 때

w12**(1)

1은 다음층의 첫번 째 뉴런

2는 앞 층의 2번째 뉴런

(1)1층의 가중치

In [30]:
x=np.array([1,0.5])
w1=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
b1=np.array([0.1,0.2,0.3])

print(w1.shape)
print(x.shape)
print(b1.shape)

a1=np.dot(x,w1)+b1
print(a1)

def sigmoid(x):
  return 1/(1+np.exp(-x))

z1=sigmoid(a1)

print(z1)
print(a1)

w2=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
b2=np.array([0.1,0.2])

print(z1.shape)
print(w2.shape)
print(b2.shape)

a2=np.dot(z1,w2)+b2
z2=sigmoid(a2)

print(z2)

def identity_function(x):
  return X

w3=np.array([[0.1,0.3],[0.2,0.4]])
b3=np.array([0.1,0.2])

a3=np.dot(z2,w3)+b3
y=np.identity_function(a3) #혹은 y=a3

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]
[0.3 0.7 1.1]
(3,)
(3, 2)
(2,)
[0.62624937 0.7710107 ]


In [38]:
#신경망의 순방향 구현

import numpy as np



def init_network(): #가중치와 편향을 초기화하고 딕셔너리 변수인 network에 저장 network변수는 각 층에 필요한 매개변수를 저장
  network={}
  network['W1']=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
  network['b1']=np.array([0.1,0.2,0.3])
  network['W2']=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
  network['b2']=np.array([0.1,0.2])
  network['W3']=np.array([[0.1,0.3],[0.2,0.4]])
  network['b3']=np.array([0.1,0.2])

  return network


def forward(network,x): #입력신호를 출력으로 변환시킴
  W1,W2,W3=network['W1'],network['W2'],network['W3']
  b1,b2,b3=network['b1'],network['b2'],network['b3']

  a1=np.dot(x,W1)+b1
  z1=sigmoid(a1)
  a2=np.dot(z1,W2)+b2
  z2=sigmoid(a2)
  a3=np.dot(z2,W3)+b3
  y=identity_function(a3)

  return y

network=init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y)

[1 2]
